# NumPy is a Python library for numerical computing that provides support for arrays and matrices. 
	Here is a tutorial that covers some of the most commonly used NumPy methods:

    np.array: Converts input data into an ndarray.

    np.zeros: Returns a new array of given shape and type, filled with zeros.

    np.ones: Returns a new array of given shape and type, filled with ones.

    np.eye: Returns a 2-D array with ones on the diagonal and zeros elsewhere.

    np.linspace: Returns evenly spaced numbers over a specified interval.

    np.arange: Returns evenly spaced values within a given interval.

    np.random.rand: Generates arrays of random values in a given shape.

    np.reshape: Gives a new shape to an array without changing its data.

    np.transpose: Permutes the dimensions of an array.

    np.concatenate: Joins two or more arrays along an existing axis.

    np.split: Splits an array into multiple sub-arrays along a given axis.

    np.mean: Computes the arithmetic mean along the specified axis.

    np.median: Computes the median along the specified axis.

    np.corrcoef: Computes Pearson product-moment correlation coefficients.

    np.cov: Estimates a covariance matrix, given two sets of random variables.


# **ndarray**

ndarray stands for "N-dimensional array." It is the fundamental data structure in NumPy and is used to store and manipulate large arrays of homogeneous data (data of the same type, such as integers or floating-point values). The ndarray is a fast, flexible, and memory-efficient alternative to Python's built-in lists, and it provides many useful methods for working with arrays, such as reshaping, indexing, and mathematical operations. The dimensionality of an ndarray is specified by its "shape," which is a tuple of integers representing the size of each dimension.


# **is ndarray an array or matrix**

An ndarray can represent both arrays and matrices. It is a multi-dimensional, homogeneous collection of elements, which can be either a one-dimensional array (vector) or a two-dimensional array (matrix), or even higher-dimensional arrays with more than two dimensions. The distinction between an array and a matrix is often based on the context in which they are used. In general, arrays are used to store sequences of elements, while matrices are used to represent two-dimensional numerical tables. However, in NumPy, the term "ndarray" is used to refer to arrays of any dimensionality, including both arrays and matrices.

# **is numpy mostly used for arrays**

Yes, NumPy is mostly used for arrays, specifically for arrays of numerical data. NumPy provides a powerful and efficient library for working with arrays, including functions for performing element-wise operations, linear algebra operations, statistical operations, and many more. The ndarray data structure in NumPy is designed specifically for working with arrays and is optimized for numerical computations, making it an ideal choice for scientific and mathematical applications. Additionally, NumPy integrates well with other scientific libraries such as SciPy and Matplotlib, making it a popular choice for scientific computing and data analysis in Python.


# **is numpy array and vector is same**

In a broad sense, the terms "NumPy array" and "vector" can be used interchangeably, as a vector is simply a one-dimensional array. However, in a more specific sense, the term "vector" is often used to refer to a mathematical object with specific properties and operations, such as the concept of a vector in linear algebra.

In NumPy, a one-dimensional array can be treated as a vector, as NumPy provides functions for performing vector operations, such as dot products and vector norms. However, it's important to note that not all one-dimensional arrays in NumPy are necessarily vectors in the mathematical sense.

In summary, while the terms "NumPy array" and "vector" are often used interchangeably, it's important to understand the specific context in which they are used and the mathematical properties they may or may not possess.

In [ ]:
# LIST MOST POPULAR WAYS TO CREATE NDARRY WITH EXAMPLES 

  # There are several ways to create an ndarray in NumPy, including:

  

# 1> USING THE ARRAY FUNCTION : You can create an ndarray from a list or a tuple using the array function. For example:


import numpy as np

# Creating an ndarray from a list
a = np.array([1, 2, 3, 4, 5])
print(a)

# Output: [1 2 3 4 5]

# Creating an ndarray from a tuple
b = np.array((1, 2, 3, 4, 5))
print(b)
# Output: [1 2 3 4 5]

c=np.array([3,4,5,6,7])
print(c)

[1 2 3 4 5]
[1 2 3 4 5]
[3 4 5 6 7]


In [ ]:
# 2> USING THE ZEROS FUNCTIONS : You can create an ndarray filled with zeros using the zeros function. For example:
import numpy as np

# Creating a 3x3 ndarray filled with zeros
a = np.zeros((3, 3))
print(a)

a = np.zeros([5, 5])
print(a)
# Output:
# [[0. 0. 0.]
#  [0. 0. 0.]
#  [0. 0. 0.]]



[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
# 3> USING THE ONES FUNCTION : You can create an ndarray filled with ones using the ones function. For example:
import numpy as np

# Creating a 3x3 ndarray filled with ones
a = np.ones((3, 3))
print(a)

z = np.ones([4,4])
print(z)
# Output:
# [[1. 1. 1.]
#  [1. 1. 1.]
#  [1. 1. 1.]]


[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
# 4> USING THE ARANGE FUNCTION : You can create an ndarray with a range of values using the arange function. For example:

import numpy as np

# Creating an ndarray with values from 0 to 9
a = np.arange(10)
print(a)


z = np.arange(7)
print(z)
# Output: [0 1 2 3 4 5 6 7 8 9]


[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6]


In [ ]:
# 5> Using linspace: "numpy.linspace() is a function that returns evenly spaced numbers over a specified interval in numpy."

import numpy as np

# Creating an ndarray with values from 0 to 9, with 5 values in between
a = np.linspace(0, 9, 5)
print(a)



# Output: [0.  2.5 5.  7.5 9. ]


In [ ]:
#  logspace: "numpy.logspace() is a function that returns numbers spaced evenly on a log scale over a specified interval in numpy."
import numpy as np

# Creating an ndarray with values from 10^1 to 10^3, with 5 values in between
a = np.logspace(1, 3, 5)
print(a)

# Output: [ 10.          31.6227766   100.         316.22776602 1000.        ]


In [ ]:
#  eye: "numpy.eye() is a function that returns a 2-D array with ones on the diagonal and zeros elsewhere in numpy."

import numpy as np

# Creating a 3x3 identity matrix
a = np.eye(3)
print(a)

# Output:
# [[1. 0. 0.]
#  [0. 1. 0.]
#  [0. 0. 1.]]


In [ ]:
#  empty:"numpy.empty() is a function that returns a new array of given shape and type, without initializing entries in numpy."

import numpy as np

# Creating an empty 3x3 ndarray
a = np.empty((3, 3))
print(a)

# Output:
# [[0. 0. 0.]
#  [0. 0. 0.]
#  [0. 0. 0.]]


In [1]:
#  full: "numpy.full() is a function that returns a new array of given shape and type, with all entries set to the fill value in numpy."


import numpy as np

# Creating a 3x3 ndarray filled with 7s
a = np.full((3, 3), 7)
print(a)

# Output:
# [[7 7 7]
#  [7 7 7]
#  [7 7 7]]


[[7 7 7]
 [7 7 7]
 [7 7 7]]
