In [1]:
import numpy as np

In [16]:
# creating array

# 1-Conversion from other Python structures (i.e. lists and tuples)

# OR

# created numpy array with python list

# OR


# 1. creating numpy array using python object
myarr = np.array([3,6,45,6]) # 1 D ARRAY
myarr


array([ 3,  6, 45,  6])

In [15]:
myarr[0] 

3

In [18]:
# int32 , int64 : we have memory management at hand
myarr2 = np.array([[3,6,45,6]],dtype=np.int8)  # 2 D ARRAY 
myarr2

array([[ 3,  6, 45,  6]], dtype=int8)

In [17]:
myarr2[0,1]

6

In [22]:
myarr2.shape

(1, 4)

In [23]:
myarr2.dtype

# In Most Cases : int64 , int32 int8  will be used

dtype('int8')

In [24]:
myarr2[0,1] =100 # changing an element

In [25]:
myarr2

array([[  3, 100,  45,   6]], dtype=int8)