In [7]:
# 2-Intrinsic NumPy array creation functions (e.g. arange, ones, zeros, etc.)

# numpy provide some functions for creating array


# zeros function
import numpy as np 
zeros = np.zeros((2,5))
zeros # ye 2,5 size ka array bana k dega filled with zeros
# zeros.dtype


dtype('float64')

In [13]:
# arange function 
import numpy as np 
rng=np.arange(15)
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [16]:
# linspace function
import numpy as np 
lspace = np.linspace(1,50,10) # give 10 elements : elements between 1 to 50 having equal space between them

lspace  

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [17]:
# empty function
import numpy as np
emp = np.empty((4,6)) # empty array of 4,6 , all values will be random 
emp

array([[4.65774186e-310, 0.00000000e+000, 6.93758456e-310,
        6.93758457e-310, 6.93758441e-310, 6.93758457e-310],
       [6.93758441e-310, 6.93758456e-310, 6.93758451e-310,
        6.93758457e-310, 6.93758457e-310, 6.93758447e-310],
       [6.93758441e-310, 6.93758457e-310, 6.93758446e-310,
        6.93758457e-310, 6.93758447e-310, 6.93758447e-310],
       [6.93758446e-310, 6.93758457e-310, 6.93758446e-310,
        6.93758447e-310, 6.93758457e-310, 6.93758441e-310]])

In [18]:
# empty_like function 

emp_like = np.empty_like(lspace) # kisi old array ka size copy krke ye empty array banadega
emp_like

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [19]:
ide = np.identity(45) # gives 45 X 45 matrix ki identity  matrix 
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [20]:
ide.shape

(45, 45)

In [28]:
import numpy as np
arr = np.arange(99)
arr.reshape(3,33)
# arr.reshape(3,31) # ERROR  3*31 will be 93 not 99 
arr = arr.ravel()
arr.shape # now this has become a 1 D array of 99 element 

(99,)