In [3]:
# NUMPY AXIS :

# 1 D ARRAY -> [1,2,3,4,5]  -> No of Axis = 1  -> [ Axis 0]

# 2 D ARRAY -> [[1,2,3],[4,5,6]]  -> No of Axis = 2 -> [ Axis 0] [ Axis 1]

# Numpy me axis 0 se start hoti hai                          


#                      [axis 1 columns]         [sum at axis 0]        
#     [axis 0 rows]      1   2   3                     6
#                        4   5   6                     15            
#               
#     [sum at axis 0]    5   7   9

In [ ]:
# Jo one dimensional array hota hai , wo thoda sa confusing hota hai , usme sirf 1 axis hoti hai 

In [10]:
import numpy as np
x= [[1,2,3],[4,5,6]]
ar = np.array(x)
ar
ar.sum(axis=0)
ar.sum(axis=1)

array([ 6, 15])

In [11]:
ar.T # this will transpose our array

array([[1, 4],
       [2, 5],
       [3, 6]])

In [14]:
ar.flat # will give us a iterator 

for item in ar.flat:
    print(item)

1
2
3
4
5
6


In [16]:
ar.ndim # no of dimensions 

2

In [17]:
ar.size # no of elements  ,think (here size is an attribute argmax is a function) (attribute vs function)

6

In [18]:
ar.nbytes # gives us total( bytes,memory,space )  consumed by our array 

48

In [20]:
one = np.array([2,43,45,32,2,5])
one.argmax() # gives the index of maximum element here(45)

2

In [22]:
one.argsort() # we give an array of (sorted index)

array([0, 4, 5, 3, 1, 2])

In [23]:
ar.argmin() # oth index pr min element hai

0

In [24]:
ar.argmax(axis=0)

array([1, 1, 1])

In [25]:
ar.argmax(axis=1)

array([2, 2])

In [26]:
ar.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2]])