In [4]:
import numpy as np

ar = np.array([[1,2,3],[4,5,6],[7,1,0]]) 
ar2 = np.array([[1,2,1],[4,0,6],[8,1,0]])

ar+ar2

array([[ 2,  4,  4],
       [ 8,  5, 12],
       [15,  2,  0]])

In [6]:
# We cannot above thing with list 
[324,34]+[34,546] # iss list extend hoja rahi hai 

[324, 34, 34, 546]

In [7]:
ar * ar2 # ye element wise multiplication krdega

array([[ 1,  4,  3],
       [16,  0, 36],
       [56,  1,  0]])

In [9]:
np.sqrt(ar) # ye element wise sqrt nikal dega 

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [10]:
ar.sum()

29

In [11]:
ar.max()

7

In [12]:
ar.min()

0

In [13]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [14]:
np.where(ar>5) # (array([1, 2]), array([2, 0])) pr greater than 5 hai 
                # isne arrays ka tuple return kr diya 

(array([1, 2]), array([2, 0]))

In [16]:
np.count_nonzero(ar) # ye sum krke de dega kitne non zero element hai hamare pass 


8

In [17]:
np.nonzero(ar) # ye har dimension k liye ek tuple dega  

(array([0, 0, 0, 1, 1, 1, 2, 2]), array([0, 1, 2, 0, 1, 2, 0, 1]))

In [20]:
# numpy saves memory : (32 vs 112)  size comparison of numpy array vs python array 
import sys 
py_ar = [0,4,55,2] # python array


In [21]:
import numpy as np 
np_ar = np.array(py_ar)

In [22]:
sys.getsizeof(1) * len(py_ar)

112

In [24]:
np_ar.itemsize * np_ar.size

32